### ISSUE TITLE
Error with sendTransaction RPC request to wallet daemon

### ISSUE THREAD

**Issue by k7n2g** [derogold/derogold-pool#1]
I have this error in the pool  
 Payments splintered and 0 successfully sent, 1 failed
2022-03-01 21:44:56 [payments] Payments processing failed: null

 Error with sendTransaction RPC request to wallet daemon {} [payments] Payments failed to send to {"amount":xxxxxx,"address":"dg4CaC7iE4GDS63C9kmYaKJuahTsVbqFncpwobKnYFoCLg2oLqZ18dTe6KXocjiAPg5PXTnobKL7nBxji4P1qnqZ1qyKxRwoR"}

nothing useful in logs

have I opened the pool wallet correctly  anyone have the correct code they use to open the pool wallet so I can check, please

**Comment by LeoStehlik** [comment]
yes, unfortunately it does take a good level of technical knowledge to run the Pool -> Node; Pool -> PaymentGateway -> Node relationships. The pool code works, the wallet-service and wallet-api code works, the daemon works, and it all works alltogether integrated (I run two pools myself in two different locations). Therefore, the problem might be you don't understand this well. If you need any help making it work, join our Discord and ask in the #dev-help channel there.

**Comment by k7n2g** [comment]
Thanks you LeoStehlik  will do

**Comment by k7n2g** [comment]
Hello, leoStehlik i can't find  tech on discord but one of my servers with the up-to-date code is showing this error FATAL   Caught JSON exception, likely missing required json parameter: JSON parameter is wrong type. Expected uint64_t, got Null 
I believe this is a field error but I can't find it do you have an update if this has happened before be much obliged if you can help with it

**Comment by LeoStehlik** [comment]
Check your nodejs version, it’s most likely that. 
This code was not maintained for quite a few years, so it is known to work with Node 10.x. 
Lol, responding to your comments 2 years later haha. Have not been around in this nonsense for quite a few years.
